version: '3'
name: orbital-sync
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    environment:
      PRIMARY_HOST_BASE_URL: 'Base URL of Main Pihole instance:1010'
      PRIMARY_HOST_PASSWORD: 'Password of Main PiHole instance'
      SECONDARY_HOST_1_BASE_URL: 'Base URL of second Pihole instance:1010'
      SECONDARY_HOST_1_PASSWORD: 'Password of Second Pihole instance'
      RUN_ONCE: true
      #INTERVAL_MINUTES: 30
      SYNC_LOCALDNSRECORDS: true
      SYNC_LOCALCNAMERECORDS: true