version: '3.8'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - /portainer/Files/AppData/Config/uptime-kuma:/app/data
    #ports:
    #  - "3001:3001"  # <Host Port>:<Container Port>
    #  - "3307:3306"
    command: "node server/server.js"
    environment:
      - "NODE_VERSION=16.20.0"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "YARN_VERSION=1.22.19"
    entrypoint: "/usr/bin/dumb-init -- extra/entrypoint.sh"
    network_mode: "bridge"
    restart: "unless-stopped"
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptimekuma.entrypoints: "web"
      traefik.http.routers.uptimekuma.rule: "Host(`uptime.rpi-clu-001.local`)"