version: "2"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      #- UMASK_SET=022 #optional
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin/config:/config
      - /portainer/Files/AppData/Config/Jellyfin/transcode:/transcode
      - /srv/dev-disk-by-uuid-3c9c6002-dd3a-4f4c-8031-6752c4c6f2a5/Serier:/tv
      - /srv/dev-disk-by-uuid-3c9c6002-dd3a-4f4c-8031-6752c4c6f2a5/Filmer:/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped