version: '3'
name: orbital-sync
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    environment:
      PRIMARY_HOST_BASE_URL: 'https://pihole1.example.com'
      PRIMARY_HOST_PASSWORD: 'your_password1'
      SECONDARY_HOST_1_BASE_URL: 'https://pihole2.example.com'
      SECONDARY_HOST_1_PASSWORD: 'your_password2'
      RUN_ONCE: true
      #INTERVAL_MINUTES: 30
      SYNC_LOCALDNSRECORDS: true
      SYNC_LOCALCNAMERECORDS: true
      SYNC_FLUSHTABLES: true