ansible_user: pi
ansible_password: raspberry # only used on first run
ansible_python_interpreter: /usr/bin/python3
github_user_for_ssh_key: annorberg98
timezone: "Europe/Stockholm"
static_dns: "1.1.1.1"
pihole_ha_mode: no
#pihole_vip_ipv4: "192.168.50.10/24"
#pihole_vip_ipv6: "fd00::10/64"
sync_target: "{{ pihole_vip_ipv4.split('/')[0] }}"
compose_folder: "/home/anton/Desktop/Projects/Selfhosting/compose/"
raspbian_enable_bluetooth: no
reboot_after_update: no
UserKnownHostsFile: /dev/null
StrictHostKeyChecking: no
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'