services:
  traefik:
    command:
      - "traefik"
    container_name: "traefik"
    entrypoint:
      - "/entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "7b92793bb4aa"
    image: "traefik:latest"
    ipc: "private"
    labels:
      org.opencontainers.image.description: "A modern reverse-proxy"
      org.opencontainers.image.documentation: "https://docs.traefik.io"
      org.opencontainers.image.source: "https://github.com/traefik/traefik"
      org.opencontainers.image.title: "Traefik"
      org.opencontainers.image.url: "https://traefik.io"
      org.opencontainers.image.vendor: "Traefik Labs"
      org.opencontainers.image.version: "v2.10.4"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "bridge"
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
      - "8080:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - "/portainer/Files/AppData/Config/traefik/acme.json:/acme.json"
      - "/portainer/Files/AppData/Config/traefik/config.yml:/config.yml"
      - "/portainer/Files/AppData/Config/traefik/traefik.yml:/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
version: "3.6"
